### ISSUE TITLE
"hide icon from drawer" in App info don't show on lollipop

### ISSUE THREAD

**Issue by ghost** [theknut/XposedGELSettings#117]
on lollipop,Setting use white color background,which makes "hide icon from drawer" disappear.When I use black cm theme,change background from white to black,and then that option shows again.

**Comment by theknut** [comment]
Thanks for the reminder, I'll fix that!
Am 03.05.2015 06:29 schrieb "darkgentry" <notifications@github.com>:

**Comment by theknut** [comment]
I've tried to fix it but it doesn't seem like my approach is taking affect. I'll talk to a fellow about the problem and will fix it later.

**Comment by theknut** [comment]
I finally looked into it, it'll be in the next release! Thank you!
