### ISSUE TITLE
xposed error: java.lang.NullPointerException

### ISSUE THREAD

**Issue by darkgentry** [theknut/XposedGELSettings#118]
google app 4.5.13.19.arm version
05-13 09:10:08.166 E/Xposed  ( 1954): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
05-13 09:10:08.166 E/Xposed  ( 1954): 	at de.theknut.xposedgelsettings.hooks.general.ContextMenu.isWidget(ContextMenu.java:713)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at de.theknut.xposedgelsettings.hooks.general.ContextMenu.setupMenuItems(ContextMenu.java:277)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at de.theknut.xposedgelsettings.hooks.general.ContextMenu.access$400(ContextMenu.java:59)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at de.theknut.xposedgelsettings.hooks.general.ContextMenu$2.setupContextMenu(ContextMenu.java:166)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at de.theknut.xposedgelsettings.hooks.general.ContextMenu$2.beforeHookedMethod(ContextMenu.java:156)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:664)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at com.android.launcher3.Launcher.onLongClick(Unknown Source)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at android.view.View.performLongClick(View.java:4795)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at com.android.launcher3.kj.performLongClick(PagedView.java:2341)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at android.view.View$CheckForLongPress.run(View.java:19722)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at android.os.Handler.handleCallback(Handler.java:739)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at android.os.Looper.loop(Looper.java:135)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at java.lang.reflect.Method.invoke(Native Method)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at java.lang.reflect.Method.invoke(Method.java:372)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
05-13 09:10:08.166 E/Xposed  ( 1954): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)

**Comment by theknut** [comment]
Fixed in V2.3.5.
