### ISSUE TITLE
Nav and Status Bar bug

### ISSUE THREAD

**Issue by Massi-X** [theknut/XposedGELSettings#120]
Hi Theknut! I'm also here!
As you can see, XGEL has problems with bars, nothing is shown in Xposed log and the logcat. Tried to disable all other modules and nothing change, but if I disable XGEL the bug disappear.

![screenshot_2015-05-21-21-23-30](https://cloud.githubusercontent.com/assets/7504132/8128107/7054eb1a-10fc-11e5-88aa-775b835af195.png)
![screenshot_2015-06-09-23-08-21](https://cloud.githubusercontent.com/assets/7504132/8128108/70763c16-10fc-11e5-8e75-032ce1680a83.png)

**Comment by Massi-X** [comment]
Well done theknut
It's been a nice ride 😉

**Comment by theknut** [comment]
It was a wild ride, thank you Massi-X. Sometimes I think back about the
time ;)

Am Do., 24. Sept. 2020 um 21:09 Uhr schrieb Massi-X <
notifications@github.com>:
